apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: model-api # 네임스페이스 추가(일부러 deployment.yaml에서 네임스페이스 안쓰고 여기서만 씀)

resources:
  - ../../base
  - service.yaml
  - ingress.yaml
