apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: burakince/mlflow:3.7.0 # postgreSQL 연결이 되는 버전 이미지
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_S3_ENDPOINT_URL # S3 url
              value: https://s3.ap-northeast-2.amazonaws.com
            - name: AWS_DEFAULT_REGION # AWS 지역
              value: ap-northeast-2
            - name: AWS_ACCESS_KEY_ID # Access Key
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY # Secret Access Key
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
          command:
            - mlflow
            - server
            - --host=0.0.0.0
            - --port=5000
            - --default-artifact-root=s3://kube-ml-bucket/mlflow-artifacts # 모델 저장
            - --backend-store-uri=postgresql://mlflow:1234@mlflow-db:5432/mlflow
            - --allowed-hosts=mlflow.mlflow.svc.cluster.local,localhost,localhost:5000,mlflow.swmlops.site # 풀 DNS, localhost, 도메인 허용

