name: CD (Local)

on:
  push:
    branches:
      - main
    paths:
      - 'services/model-api/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: kubectl apply
        run: kubectl apply -k k8s/model-api/overlays/local/

      - name: 파드 재시작 # (이미지 태그가 계속 latest여도 새 이미지로 배포되도록)
        run: kubectl rollout restart deployment/model-api

      - name: 배포 확인
        run: kubectl rollout status deployment/model-api
